# Generated by Django 5.0.14 on 2026-10-06 20:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por postulante'), ('ENTREGADA', 'Entregada (adopción finalizada)')], db_index=True, default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('mensaje_postulante', models.TextField(blank=True, help_text='Por qué quiere adoptar a esta mascota', verbose_name='Mensaje del postulante')),
                ('respuestas_cuestionario', models.JSONField(blank=True, default=dict, verbose_name='Respuestas cuestionario')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('observaciones_revision', models.TextField(blank=True, verbose_name='Observaciones de revisión')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Adopción',
                'verbose_name_plural': 'Solicitudes de Adopción',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADOPTANTE', 'Adoptante'), ('ALBERGUE', 'Albergue'), ('ADMIN', 'Administrador')], db_index=True, default='ADOPTANTE', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('acepto_terminos', models.BooleanField(default=False, verbose_name='Aceptó términos')),
                ('fecha_aceptacion_terminos', models.DateTimeField(blank=True, null=True, verbose_name='Fecha aceptación términos')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdoptanteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_tipo', models.CharField(default='DNI', max_length=20, verbose_name='Tipo documento')),
                ('documento_numero', models.CharField(max_length=20, unique=True, verbose_name='Número documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('distrito', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('tipo_vivienda', models.CharField(blank=True, help_text='Casa, departamento, quintas, etc.', max_length=50, verbose_name='Tipo de vivienda')),
                ('tiene_patio', models.BooleanField(default=False, verbose_name='Tiene patio/área exterior')),
                ('tiene_otras_mascotas', models.BooleanField(default=False, verbose_name='Tiene otras mascotas')),
                ('detalles_otras_mascotas', models.TextField(blank=True, verbose_name='Detalle otras mascotas')),
                ('experiencia_previa', models.TextField(blank=True, verbose_name='Experiencia previa con mascotas')),
                ('motivo_adopcion', models.TextField(blank=True, verbose_name='Motivo de adopción')),
                ('preferencia_especie', models.CharField(blank=True, choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('OTRO', 'Otro')], max_length=10, verbose_name='Preferencia especie')),
                ('preferencia_tamanio', models.CharField(blank=True, choices=[('PEQUENO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=10, verbose_name='Preferencia tamaño')),
                ('preferencia_edad', models.CharField(blank=True, help_text='Ej: cachorro, joven, adulto, senior', max_length=50, verbose_name='Preferencia edad')),
                ('cuestionario_completado', models.BooleanField(default=False, verbose_name='Cuestionario completado')),
                ('fecha_cuestionario', models.DateTimeField(blank=True, null=True, verbose_name='Fecha cuestionario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoptante_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Adoptante',
                'verbose_name_plural': 'Perfiles de Adoptantes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_tipo', models.CharField(default='DNI', max_length=20, verbose_name='Tipo documento')),
                ('documento_numero', models.CharField(max_length=20, unique=True, verbose_name='Número documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('distrito', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('tipo_vivienda', models.CharField(blank=True, help_text='Casa, departamento, quintas, etc.', max_length=50, verbose_name='Tipo de vivienda')),
                ('tiene_patio', models.BooleanField(default=False, verbose_name='Tiene patio/área exterior')),
                ('tiene_otras_mascotas', models.BooleanField(default=False, verbose_name='Tiene otras mascotas')),
                ('detalles_otras_mascotas', models.TextField(blank=True, verbose_name='Detalle otras mascotas')),
                ('experiencia_previa', models.TextField(blank=True, verbose_name='Experiencia previa con mascotas')),
                ('motivo_adopcion', models.TextField(blank=True, verbose_name='Motivo de adopción')),
                ('preferencia_especie', models.CharField(blank=True, choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('OTRO', 'Otro')], max_length=10, verbose_name='Preferencia especie')),
                ('preferencia_tamanio', models.CharField(blank=True, choices=[('PEQUENO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=10, verbose_name='Preferencia tamaño')),
                ('preferencia_edad', models.CharField(blank=True, help_text='Ej: cachorro, joven, adulto, senior', max_length=50, verbose_name='Preferencia edad')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=15, verbose_name='Estado')),
                ('observaciones_internas', models.TextField(blank=True, verbose_name='Observaciones internas (staff)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulantes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
                'ordering': ['-creado_en'],
            },
        ),
    ]
