# Generated by Django 6.1.1 on 2026-10-06 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albergues', '0001_initial'),
        ('mascotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_tipo', models.CharField(default='DNI', max_length=20, verbose_name='Tipo documento')),
                ('documento_numero', models.CharField(max_length=20, unique=True, verbose_name='Número documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('distrito', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('tipo_vivienda', models.CharField(blank=True, help_text='Casa, departamento, quintas, etc.', max_length=50, verbose_name='Tipo de vivienda')),
                ('tiene_patio', models.BooleanField(default=False, verbose_name='Tiene patio/área exterior')),
                ('tiene_otras_mascotas', models.BooleanField(default=False, verbose_name='Tiene otras mascotas')),
                ('detalles_otras_mascotas', models.TextField(blank=True, verbose_name='Detalle otras mascotas')),
                ('experiencia_previa', models.TextField(blank=True, verbose_name='Experiencia previa con mascotas')),
                ('motivo_adopcion', models.TextField(blank=True, verbose_name='Motivo de adopción')),
                ('preferencia_especie', models.CharField(blank=True, choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('OTRO', 'Otro')], max_length=10, verbose_name='Preferencia especie')),
                ('preferencia_tamanio', models.CharField(blank=True, choices=[('PEQUENO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=10, verbose_name='Preferencia tamaño')),
                ('preferencia_edad', models.CharField(blank=True, help_text='Ej: cachorro, joven, adulto, senior', max_length=50, verbose_name='Preferencia edad')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=15, verbose_name='Estado')),
                ('observaciones_internas', models.TextField(blank=True, verbose_name='Observaciones internas (staff)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulantes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por postulante'), ('ENTREGADA', 'Entregada (adopción finalizada)')], db_index=True, default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('mensaje_postulante', models.TextField(blank=True, help_text='Por qué quiere adoptar a esta mascota', verbose_name='Mensaje del postulante')),
                ('respuestas_cuestionario', models.JSONField(blank=True, default=dict, verbose_name='Respuestas cuestionario')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('observaciones_revision', models.TextField(blank=True, verbose_name='Observaciones de revisión')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('albergue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='albergues.albergue', verbose_name='Albergue')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='mascotas.mascota', verbose_name='Mascota')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='acceso.postulante', verbose_name='Postulante')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Adopción',
                'verbose_name_plural': 'Solicitudes de Adopción',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['documento_numero'], name='acceso_post_documen_961f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['estado'], name='acceso_post_estado_c76772_idx'),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['email'], name='acceso_post_email_b71d61_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudadopcion',
            index=models.Index(fields=['albergue', 'estado'], name='acceso_soli_albergu_44c80c_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudadopcion',
            index=models.Index(fields=['postulante', 'estado'], name='acceso_soli_postula_97d175_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudadopcion',
            index=models.Index(fields=['mascota', 'estado'], name='acceso_soli_mascota_c4abd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudadopcion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'EN_REVISION'])), fields=('postulante', 'mascota'), name='unique_pending_solicitud_per_mascota'),
        ),
    ]
