# Generated by Django 5.0.14 on 2026-10-06 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceso', '0001_initial'),
        ('albergues', '0001_initial'),
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='albergue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='albergues.albergue', verbose_name='Albergue'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='mascotas.mascota', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='postulante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='acceso.postulante', verbose_name='Postulante'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['documento_numero'], name='acceso_post_documen_961f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['estado'], name='acceso_post_estado_c76772_idx'),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['email'], name='acceso_post_email_b71d61_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudadopcion',
            index=models.Index(fields=['albergue', 'estado'], name='acceso_soli_albergu_44c80c_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudadopcion',
            index=models.Index(fields=['postulante', 'estado'], name='acceso_soli_postula_97d175_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudadopcion',
            index=models.Index(fields=['mascota', 'estado'], name='acceso_soli_mascota_c4abd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudadopcion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'EN_REVISION'])), fields=('postulante', 'mascota'), name='unique_pending_solicitud_per_mascota'),
        ),
    ]
