# Generated by Django 5.0.14 on 2026-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptanteprofile',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='adoptanteprofile',
            name='documento_numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número documento'),
        ),
        migrations.AlterField(
            model_name='adoptanteprofile',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
    ]
