# Generated by Django 6.1.1 on 2026-10-06 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albergues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código interno')),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('OTRO', 'Otro')], max_length=10, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('sexo', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('tamanio', models.CharField(blank=True, choices=[('PEQUENO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=10, verbose_name='Tamaño')),
                ('edad_anos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad (años)')),
                ('edad_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad (meses)')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_PROCESO', 'En Proceso'), ('ADOPTADO', 'Adoptado')], db_index=True, default='DISPONIBLE', max_length=15, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Historia')),
                ('esterilizado', models.BooleanField(default=False, verbose_name='Esterilizado')),
                ('vacunas_al_dia', models.BooleanField(default=False, verbose_name='Vacunas al día')),
                ('desparasitado', models.BooleanField(default=False, verbose_name='Desparasitado')),
                ('necesidades_especiales', models.TextField(blank=True, verbose_name='Necesidades especiales')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto principal')),
                ('fotos_adicionales', models.JSONField(blank=True, default=list, verbose_name='Fotos adicionales')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('fecha_adopcion', models.DateField(blank=True, null=True, verbose_name='Fecha de adopción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('albergue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='albergues.albergue', verbose_name='Albergue')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['albergue', 'estado'], name='mascotas_ma_albergu_c80817_idx'), models.Index(fields=['estado', 'especie'], name='mascotas_ma_estado_639520_idx')],
            },
        ),
    ]
