# Generated by Django 6.1.1 on 2026-10-05 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Albergue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('capacidad_maxima', models.PositiveIntegerField(default=0, verbose_name='Capacidad máxima')),
                ('horario_atencion', models.CharField(blank=True, max_length=100, verbose_name='Horario de atención')),
                ('responsable_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del responsable')),
                ('responsable_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del responsable')),
                ('responsable_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del responsable')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='albergue', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario')),
            ],
            options={
                'verbose_name': 'Albergue',
                'verbose_name_plural': 'Albergues',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEPCION', 'Recepción'), ('OFICINA', 'Oficina administrativa'), ('ZONA_CUARENTENA', 'Zona de cuarentena'), ('ZONA_CACHORROS', 'Zona de cachorros'), ('ZONA_ADULTOS', 'Zona de adultos'), ('ZONA_GATOS', 'Zona de gatos'), ('ENFERMERIA', 'Enfermería / Veterinaria'), ('QUIROFANO', 'Quirófano'), ('ALMACEN', 'Almacén de insumos'), ('PATIO', 'Patio / Área de recreación'), ('BAÑOS', 'Baños / Lavaderos'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de área')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre / Identificador')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metros cuadrados')),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad (animales)')),
                ('equipamiento', models.TextField(blank=True, verbose_name='Equipamiento / Observaciones')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('albergue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infraestructura', to='albergues.albergue', verbose_name='Albergue')),
            ],
            options={
                'verbose_name': 'Infraestructura',
                'verbose_name_plural': 'Infraestructura',
                'ordering': ['albergue', 'tipo', 'nombre'],
                'unique_together': {('albergue', 'tipo', 'nombre')},
            },
        ),
    ]
